GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "String",
    "author": "String",
    "url": "String",
    "likes": 2
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "drakeee",
    "password": "scott",
    "name": "drake"
}
###
GET http://localhost:3003/api/users