GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hbnVhbF90ZXN0X3VzZXIiLCJpZCI6IjY1MTlmODFlZDk3ZmQ0OGIzODk0MTk3YyIsImlhdCI6MTY5NjIwNDA1NH0.LUDc96h_3TxyGdS2HjUkWPebWumMaHSqQ3OSOBDhZk4

{
    "title": "Tuesday",
    "author": "IDK",
    "url": "342erth546ufg",
    "likes": 2
}
###
DELETE http://localhost:3003/api/blogs/6525da7d37f4ffde7dd76d1c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hbnVhbF90ZXN0X3VzZXIiLCJpZCI6IjY1MTlmODFlZDk3ZmQ0OGIzODk0MTk3YyIsImlhdCI6MTY5NjIwNDA1NH0.LUDc96h_3TxyGdS2HjUkWPebWumMaHSqQ3OSOBDhZk4
###
PUT http://localhost:3003/api/blogs/6525de2e99efba3ef35c0313
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hbnVhbF90ZXN0X3VzZXIiLCJpZCI6IjY1MTlmODFlZDk3ZmQ0OGIzODk0MTk3YyIsImlhdCI6MTY5NjIwNDA1NH0.LUDc96h_3TxyGdS2HjUkWPebWumMaHSqQ3OSOBDhZk4

{
    "title": "RAEREARA",
    "author": "IDK",
    "url": "342erth546ufg",
    "likes": 2
}