POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "monday2",
    "number": "555-5555555"
}
###
GET http://localhost:3001/api/persons
###
DELETE http://localhost:3001/api/persons/6501378af32cbe858576278b
###
PUT http://localhost:3001/api/persons/6501f7ae95340d5a07a2f06b
Content-Type: application/json

{
    "name": "monday",
    "number": "555-5555555"
}