POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "monday",
    "number": "123"
}
###
GET http://localhost:3001/api/persons
###
DELETE http://localhost:3001/api/persons/65013da1cfb8523dcdee5b5b