POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "monday2",
    "number": "1234556"
}
###
GET http://localhost:3001/api/persons
###
DELETE http://localhost:3001/api/persons/6501378af32cbe858576278b
###
PUT http://localhost:3001/api/persons/65013d7bcfb8523dcdee5b52
Content-Type: application/json

{
    "name": "m",
    "number": "123"
}